### ISSUE TITLE
TP1.1版本运行出现卡死情况

### ISSUE THREAD

**Issue by 1337m4n** [tangxiaofeng7/TPScan#1]
![image](https://user-images.githubusercontent.com/37396317/99877726-2cb9d180-2c3b-11eb-885a-f7fe87a9b6a4.png)
![image](https://user-images.githubusercontent.com/37396317/99877736-35120c80-2c3b-11eb-9668-f0f454fafc0d.png)
批量检测出现如上情况

**Comment by tangxiaofeng7** [comment]
下这个版本：https://github.com/tangxiaofeng7/TPScan/releases/tag/V1.1

**Comment by 1337m4n** [comment]
正是1.1,弹窗卡死




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "唐小风"<notifications@github.com&gt;; 
发送时间: 2020年11月21日(星期六) 晚上10:54
收件人: "tangxiaofeng7/TPScan"<TPScan@noreply.github.com&gt;; 
抄送: "张先森"<2602210390@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tangxiaofeng7/TPScan] TP1.1版本运行出现卡死情况 (#1)





 
下这个版本：https://github.com/tangxiaofeng7/TPScan/releases/tag/V1.1

**Comment by tangxiaofeng7** [comment]
可能你下错了，1.1已经改了，明天你再试试。

**Comment by 1337m4n** [comment]
是1.1版本，测试vps时候出现卡死情况



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "唐小风"<notifications@github.com&gt;; 
发送时间: 2020年11月21日(星期六) 晚上11:08
收件人: "tangxiaofeng7/TPScan"<TPScan@noreply.github.com&gt;; 
抄送: "张先森"<2602210390@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tangxiaofeng7/TPScan] TP1.1版本运行出现卡死情况 (#1)





 
可能你下错了，1.1已经改了，明天你再试试。

**Comment by tangxiaofeng7** [comment]
ip发来我试试

**Comment by 1337m4n** [comment]
测百度没有问题，可能是我这边的问题，谢谢唐师傅
