### ISSUE TITLE
作者，你好！win10打开闪退  1809

### ISSUE THREAD

**Issue by BeckzZzz** [tangxiaofeng7/TPScan#2]

**Comment by tangxiaofeng7** [comment]
默认是jdk8,如果是其他高版本， 单独加上 javafx 的模块就能启动了，

加上java -Dfile.encoding="UTF-8" --module-path "C:\Program Files\Java\javafx-sdk-11.0.2\lib" --add-modules "javafx.controls,javafx.fxml,javafx.web" -jar "xxx.jar"
