### ISSUE TITLE
请问大佬Linux下怎么打开？

### ISSUE THREAD

**Issue by ikelvinwoo** [tangxiaofeng7/TPScan#4]
请问大佬，我的java版本是15。尝试了下发现打不开
![图片](https://user-images.githubusercontent.com/32406016/100042224-fdc37b80-2e45-11eb-91b6-d9c764f2d8ec.png)
java8我也试了，出现这个报错
![图片](https://user-images.githubusercontent.com/32406016/100042283-1af84a00-2e46-11eb-8022-0c1cebf35fb5.png)

**Comment by tangxiaofeng7** [comment]
下载我传到Releases里的版本

**Comment by ikelvinwoo** [comment]
大佬，我下载的就是release的版本诶。求助大佬~
