### ISSUE TITLE
java -jar TPscan出现问题

### ISSUE THREAD

**Issue by 2001hurc** [tangxiaofeng7/TPScan#8]
我不懂java ，然后我的执行命令是java -jar TPscan.jar
报错是
错误: 找不到或无法加载主类 com.leishianquan.MainApp
原因: java.lang.NoClassDefFoundError: javafx/application/Application
os：parrot
java 版本：
openjdk 13.0.5.1 2020-11-06
OpenJDK Runtime Environment (build 13.0.5.1+1-Debian-1)
OpenJDK 64-Bit Server VM (build 13.0.5.1+1-Debian-1, mixed mode)
望大佬教教我怎么做

**Comment by tangxiaofeng7** [comment]
jdk改成1.8即可

**Comment by 2001hurc** [comment]
> jdk改成1.8即可

感谢，尝试了多个版本的openjdk最终使用oraclejdk 1.8成功运行
